import React, { useState } from 'react';
import { Head } from '@inertiajs/react';
import { supabase } from '../lib/supabase';

export default function Auth() {
    const [phone, setPhone] = useState(''); const [otp, setOtp] = useState(''); const [name, setName] = useState(''); const [sent, setSent] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
    const requestOtp = async (event) => { event.preventDefault(); setBusy(true); setError(''); const { error: authError } = await supabase.auth.signInWithOtp({ phone }); setBusy(false); if (authError) setError(authError.message); else setSent(true); };
    const verifyOtp = async (event) => { event.preventDefault(); setBusy(true); setError(''); const { data, error: authError } = await supabase.auth.verifyOtp({ phone, token: otp, type: 'sms' }); if (authError) { setError(authError.message); setBusy(false); return; } const response = await fetch('/auth/sync', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json', 'Accept': 'application/json', 'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.content, Authorization: `Bearer ${data.session.access_token}` }, body: JSON.stringify({ access_token: data.session.access_token, name }) }); if (!response.ok) setError('Unable to create your MediSync profile.'); else window.location.href = '/'; setBusy(false); };
    return <><Head title="Sign in" /><main className="min-h-screen bg-canvas flex items-center justify-center p-6"><div className="w-full max-w-md glass-card rounded-3xl p-8"><h1 className="text-3xl font-black text-ink">Medi<span className="text-teal-600">Sync</span></h1><p className="mt-2 text-sm text-ink/60">Sign in securely with your mobile number.</p><form onSubmit={sent ? verifyOtp : requestOtp} className="mt-8 space-y-4">{!sent && <input value={name} onChange={e=>setName(e.target.value)} placeholder="Full name (new users)" className="w-full rounded-xl border border-ink/15 px-4 py-3" />}{!sent ? <input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+60123456789" className="w-full rounded-xl border border-ink/15 px-4 py-3" /> : <input required value={otp} onChange={e=>setOtp(e.target.value)} placeholder="6-digit OTP" inputMode="numeric" className="w-full rounded-xl border border-ink/15 px-4 py-3" />} {error && <p className="text-sm text-red-600">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-teal-600 px-4 py-3 font-bold text-white disabled:opacity-50">{busy ? 'Please wait…' : sent ? 'Verify and continue' : 'Send OTP'}</button></form>{sent && <button onClick={()=>setSent(false)} className="mt-4 text-sm text-ink/60 underline">Change number</button>}</div></main></>;
}
