import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
    en: {
        language: 'Language', english: 'English', malay: 'Malay',
        header: { darkMode: 'Switch to dark mode', lightMode: 'Switch to light mode', notifications: 'Notifications', profile: 'Profile', navigation: 'Navigation', noNotifications: 'No notifications yet.', openSidebar: 'Open sidebar', closeSidebar: 'Close sidebar', collapseSidebar: 'Minimize sidebar', expandSidebar: 'Maximize sidebar', viewEmergency: 'View emergency profile', signOut: 'Sign out', signingOut: 'Signing out…' },
        welcome: { eyebrow: 'Family health coordination', title: 'Calm care, connected family.', description: 'MediSync keeps medications, appointments, documents, and emergency information together in one secure place.', getStarted: 'Get started', signIn: 'Go to sign in', medication: 'Medication support', medicationText: 'Track schedules and daily adherence.', family: 'Family connection', familyText: 'Keep caregivers in sync with important updates.', safety: 'Emergency readiness', safetyText: 'Make critical information available when it matters.' },
        dashboard: { eyebrow: 'Your health command centre', subtitle: 'Stay on top of medication, appointments, and family support in one calm overview.', profile: 'Patient profile', patient: 'Patient', bloodType: 'Blood type', iceReady: 'ICE ready', medicalProfile: 'Medical profile', medications: 'Medications', manageMedication: 'Manage all medication', careSummary: 'Care summary', emergencyReadiness: 'Emergency readiness', allergiesRecorded: 'recorded allergies', primaryIceContact: 'Primary ICE contact', progress: 'Progress', weeklyActivity: 'Weekly medication activity', medicationLogsOn: 'Medication logs on', chartLabel: 'Interactive weekly care activity chart', liveTotals: 'Live totals', activeMedications: 'Active medications', appointmentsLabel: 'Appointments', caregiversConnected: 'Caregivers connected', careChecklist: 'Care checklist', readyTogether: 'Ready together', careCalendar: 'Care calendar', previousMonth: 'Previous month', nextMonth: 'Next month', selectEvent: 'Select an event to see care details.', medicationHub: 'Medication hub', manageReminders: 'Manage reminders', doctorPrep: 'Doctor prep', summariseSymptoms: 'Summarise symptoms', safetyProfile: 'Safety profile', openIce: 'Open ICE profile' },
        medications: { title: 'Medication management & reminders', adherence: 'Medication adherence', adherenceText: 'Medication taken as scheduled', streak: 'Consistent streak', streakText: 'Consecutive days without missing', caregiverSync: 'Caregiver sync', synced: 'Automatically synced', syncedText: 'Family receives live notifications', subtitle: 'Manage daily doses and medication supply records.', heading: 'Medication & reminders', all: 'All time', morning: 'Morning', afternoon: 'Afternoon', night: 'Night', instruction: 'Instructions', remaining: 'Medication remaining', add: 'Add new medication', addTitle: 'Add medication', name: 'Medication / generic name', category: 'Medication category', dose: 'Dose (mg / tablet)', time: 'Medication time', specificTime: 'Specific time', special: 'Special instructions', cancel: 'Cancel', save: 'Save medication', take: 'Mark as taken', taken: 'Taken today', delete: 'Delete medication', deleteConfirm: 'Are you sure you want to delete this medication?', errorAdd: 'Failed to add medication. Please check your input.', errorDelete: 'Failed to delete medication.', network: 'Network error. Please try again.' },
        appointments: { title: 'Hospital & clinic appointments', subtitle: 'Cardiology, endocrinology, and regular health check-ups.', heading: 'Hospital appointment reminders', add: 'Add appointment', preparation: 'Preparation note', documents: 'Documents to bring', dateTime: 'Date & time', location: 'Clinic location', deleteConfirm: 'Are you sure you want to delete this appointment?', errorAdd: 'Failed to add appointment. Please check your input.', errorDelete: 'Failed to delete appointment.', network: 'Network error. Please try again.', subject: 'Appointment title / purpose', doctor: 'Specialist doctor name', clinic: 'Clinic / department', date: 'Date', time: 'Appointment time', notes: 'Preparation notes', cancel: 'Cancel', save: 'Save appointment', close: 'Close' },
        caregiver: { title: 'Caregiver & family sync', connected: 'Caregiver network connected', code: 'Family connection code', copy: 'Copy pairing code', copied: 'Code copied!', description: 'Family members can monitor medication schedules, hospital appointments, and receive live missed-dose alerts.', live: 'Live synced', health: 'Patient health status', morning: 'Morning medication', afternoon: 'Afternoon medication', evening: 'Evening medication', taken: 'Taken', waiting: 'Waiting', members: 'Connected family members', access: 'Access and monitoring controls.', primary: 'Primary ICE', memberSince: 'Member since', activity: 'Care activity log', by: 'By', invite: 'Invite new member', inviteTitle: 'Invite family member / caregiver', scan: 'Scan or share connection code', inviteText: 'Ask a family member to install MediSync and enter the connection code below.', copySend: 'Copy code & send via WhatsApp', close: 'Close' },
        documents: { title: 'Medical & insurance document vault', subtitle: 'Secure storage for medical cards, lab reports, and hospital records.', upload: 'Upload document', protected: 'Real-time protected storage', protectedText: 'Documents are accessible only to the patient and listed caregivers.', encrypted: 'Encrypted vault', all: 'All documents', search: 'Search documents...', uploaded: 'Uploaded', view: 'View', download: 'Download', preview: 'Secure MediSync PDF preview', previewText: 'This document is encrypted with your private medical key. No external information is exposed.', closePreview: 'Close preview', uploadTitle: 'Upload medical / insurance document', documentName: 'Document name / title', category: 'Document category', insurance: 'Insurance & medical card', labs: 'Blood & lab results', discharge: 'Hospital discharge summary', prescription: 'Medication prescription', chooseFile: 'Choose file (PDF / image)', chooseFileText: 'Click to choose a file or drag it here', fileSupport: 'PDF, PNG, JPG, WEBP up to 10MB', notes: 'Notes', notesPlaceholder: 'Additional notes about the document', cancel: 'Cancel', uploading: 'Uploading...', uploadVault: 'Upload to vault', required: 'Please enter a title and choose a file.', uploadError: 'Upload failed.', uploadNetwork: 'Error uploading file.' },
        symptoms: { title: 'Symptom summariser for doctors', eyebrow: 'Doctor appointment preparation (intake assistant)', description: 'Enter your symptoms. The system will structure a concise SOAP-style clinical report for your doctor.', form: 'Symptom notes form', primary: 'Main symptom / pain experienced', onset: 'Onset', duration: 'Duration & frequency', severity: 'Pain scale (1 - 10)', triggers: 'Triggers (when it feels worse)', accompanying: 'Other accompanying symptoms', treatments: 'Treatments / self-care tried', report: 'Doctor summary report (SOAP intake)', format: 'Clinical format', reportHint: 'Show this report directly to your doctor or nurse during medical history taking:', copy: 'Copy summary for doctor', copied: 'Summary copied!', save: 'Save report', saved: 'Saved!', history: 'Medical history summary', complaint: 'Chief complaint', onsetLabel: 'Onset', durationLabel: 'Duration', severityLabel: 'Severity', triggersLabel: 'Triggers', associated: 'Associated symptoms', pretreatments: 'Pre-treatments tried', patient: 'Patient' },
        terms: { title: 'AI medical term simplifier', eyebrow: 'Medical term & doctor report translator', heading: 'Simplify medical terms', description: 'Understand difficult medical jargon in hospital letters, lab results, and diagnosis reports using plain language and everyday analogies.', search: 'Type a medical term...', translate: 'Explain simply', easy: 'Explained in plain language', explanation: 'Simple explanation (without jargon)', analogy: 'Easy-to-understand analogy', takeaways: 'Key things to know', questions: 'Questions to ask your doctor', copyQuestions: 'Copy questions for appointment', searchResult: 'Search result', generated: 'A medical term used to describe a physical condition or laboratory result.', questionOne: 'What does this term mean for my health?', questionTwo: 'Is follow-up treatment needed?' },
        emergency: { iceTitle: 'Emergency profile management (ICE)', iceBadge: 'Emergency ICE lockscreen', iceHeading: 'In-case-of-emergency (ICE) profile', blood: 'Blood group', donor: 'Organ donor', donorYes: 'Yes (pledged)', donorNo: 'No', weight: 'Weight (kg)', height: 'Height (cm)', chronic: 'Chronic conditions & critical allergies', allergy: 'Medication & food allergies (strict warning)', history: 'Medical history / chronic conditions', medications: 'Current vital medications', purpose: 'Purpose', active: 'Active', publicAccess: 'Public access control', publicText: 'Public access mode limits personal files, insurance numbers, and confidential documents. Only life-safety data is shown.', quickLink: 'Emergency quick link', save: 'Update ICE profile', saved: 'Profile saved!', error: 'Network error. Please try again.', sosTitle: 'Emergency SOS & nearby hospitals', sosBadge: 'One-touch emergency line', sosHeading: 'SOS & nearby hospital finder', sosText: 'Press the emergency button below to share your current location and send an automatic emergency SMS to your caregiver and nearby hospital line.', press: 'Press SOS', alert: 'Emergency alert broadcast!', sent: 'SMS & location sent to caregiver', sending: 'Sending GPS coordinates & ICE information...', cancel: 'Cancel SOS alert', contacts: 'Primary emergency contacts', primary: 'Primary', hospitals: 'Nearby hospitals & emergency departments (GPS)', hospitalText: 'Red-zone hospitals near your residence.', locationActive: 'Location active', emergency24: '24-hour emergency zone', clinic: 'Health clinic', callER: 'Call ER', navigate: 'Navigate', driving: 'drive' },
    },
    ms: {
        language: 'Bahasa', english: 'Inggeris', malay: 'Melayu',
        header: { darkMode: 'Tukar kepada mod gelap', lightMode: 'Tukar kepada mod cerah', notifications: 'Pemberitahuan', profile: 'Profil', navigation: 'Navigasi', noNotifications: 'Tiada pemberitahuan lagi.', openSidebar: 'Buka bar sisi', closeSidebar: 'Tutup bar sisi', collapseSidebar: 'Minimumkan bar sisi', expandSidebar: 'Maksimumkan bar sisi', viewEmergency: 'Lihat profil kecemasan', signOut: 'Log keluar', signingOut: 'Sedang log keluar…' },
        welcome: { eyebrow: 'Penyelarasan kesihatan keluarga', title: 'Penjagaan tenang, keluarga terhubung.', description: 'MediSync menyatukan ubat, temujanji, dokumen, dan maklumat kecemasan dalam satu tempat yang selamat.', getStarted: 'Mula sekarang', signIn: 'Pergi ke log masuk', medication: 'Sokongan ubat', medicationText: 'Jejaki jadual dan pematuhan harian.', family: 'Hubungan keluarga', familyText: 'Pastikan penjaga menerima kemas kini penting.', safety: 'Kesediaan kecemasan', safetyText: 'Sediakan maklumat kritikal apabila diperlukan.' },
        dashboard: { eyebrow: 'Pusat kesihatan anda', subtitle: 'Pantau ubat, temujanji, dan sokongan keluarga dalam satu ringkasan yang tenang.', profile: 'Profil pesakit', patient: 'Pesakit', bloodType: 'Kumpulan darah', iceReady: 'ICE sedia', medicalProfile: 'Profil perubatan', medications: 'Ubat harian', manageMedication: 'Urus semua ubat', careSummary: 'Ringkasan penjagaan', emergencyReadiness: 'Kesediaan kecemasan', allergiesRecorded: 'alahan direkodkan', primaryIceContact: 'Hubungan ICE utama', progress: 'Kemajuan', weeklyActivity: 'Aktiviti ubat mingguan', medicationLogsOn: 'Log ubat pada', chartLabel: 'Carta aktiviti penjagaan mingguan interaktif', liveTotals: 'Jumlah semasa', activeMedications: 'Ubat aktif', appointmentsLabel: 'Temujanji', caregiversConnected: 'Penjaga terhubung', careChecklist: 'Senarai penjagaan', readyTogether: 'Sedia bersama', careCalendar: 'Kalendar penjagaan', previousMonth: 'Bulan sebelumnya', nextMonth: 'Bulan seterusnya', selectEvent: 'Pilih acara untuk melihat butiran penjagaan.', medicationHub: 'Hab ubat', manageReminders: 'Urus peringatan', doctorPrep: 'Persediaan doktor', summariseSymptoms: 'Ringkaskan simptom', safetyProfile: 'Profil keselamatan', openIce: 'Buka profil ICE' },
        medications: { title: 'Pengurusan ubat & peringatan', adherence: 'Kadar pematuhan', adherenceText: 'Ubat diambil mengikut jadual', streak: 'Streak konsisten', streakText: 'Berturut-turut tanpa tertinggal', caregiverSync: 'Sync penjaga', synced: 'Diselaraskan automatik', syncedText: 'Keluarga menerima pemberitahuan langsung', subtitle: 'Urus dos harian dan rekod stok bekalan ubat.', heading: 'Pengurusan ubat & peringatan', all: 'Semua masa', morning: 'Pagi', afternoon: 'Tengah hari', night: 'Malam', instruction: 'Arahan', remaining: 'Baki ubat', add: 'Tambah ubat baharu', addTitle: 'Tambah ubat', name: 'Nama ubat / generik', category: 'Kategori ubat', dose: 'Dos (mg / tablet)', time: 'Waktu makan', specificTime: 'Masa khusus', special: 'Arahan khas', cancel: 'Batal', save: 'Simpan ubat', take: 'Tanda diambil', taken: 'Dimakan hari ini', delete: 'Padam ubat', deleteConfirm: 'Adakah anda pasti mahu memadam ubat ini?', errorAdd: 'Gagal menambah ubat. Sila semak input anda.', errorDelete: 'Gagal memadam rekod ubat.', network: 'Ralat rangkaian. Sila cuba lagi.' },
        appointments: { title: 'Temujanji hospital & klinik', subtitle: 'Pakar kardiologi, endokrinologi, dan pemeriksaan kesihatan berkala.', heading: 'Peringatan temujanji hospital', add: 'Tambah temujanji', preparation: 'Nota penyediaan', documents: 'Dokumen perlu dibawa', dateTime: 'Tarikh & masa', location: 'Lokasi klinik', deleteConfirm: 'Adakah anda pasti mahu memadam temujanji ini?', errorAdd: 'Gagal menambah temujanji. Sila semak input anda.', errorDelete: 'Gagal memadam temujanji.', network: 'Ralat rangkaian. Sila cuba lagi.', subject: 'Tajuk temujanji / tujuan', doctor: 'Nama doktor pakar', clinic: 'Klinik / jabatan', date: 'Tarikh', time: 'Masa temujanji', notes: 'Nota arahan peringatan', cancel: 'Batal', save: 'Simpan temujanji', close: 'Tutup' },
        caregiver: { title: 'Sambungan penjaga & keluarga', connected: 'Rangkaian penjaga disambungkan', code: 'Kod sambungan keluarga', copy: 'Salin kod pasangan', copied: 'Kod disalin!', description: 'Anak-anak dan ahli keluarga boleh memantau jadual ubat, temujanji hospital, serta menerima amaran langsung jika ubat terlupa diambil.', live: 'Diselaraskan langsung', health: 'Status kesihatan pesakit', morning: 'Ubat pagi', afternoon: 'Ubat tengah hari', evening: 'Ubat malam', taken: 'Dimakan', waiting: 'Menunggu', members: 'Ahli keluarga terhubung', access: 'Pilihan akses dan kawalan pemantauan.', primary: 'ICE utama', memberSince: 'Ahli sejak', activity: 'Log aktiviti penjagaan', by: 'Oleh', invite: 'Jemput ahli baharu', inviteTitle: 'Jemput ahli keluarga / penjaga', scan: 'Imbas atau kongsi kod sambungan', inviteText: 'Minta ahli keluarga memasang MediSync dan memasukkan kod sambungan di bawah.', copySend: 'Salin kod & hantar melalui WhatsApp', close: 'Tutup' },
        documents: { title: 'Vault dokumen perubatan & insurans', subtitle: 'Storan selamat bagi kad perubatan, laporan makmal, dan rekod hospital.', upload: 'Muat naik dokumen', protected: 'Storan dilindungi masa nyata', protectedText: 'Dokumen hanya boleh diakses oleh pesakit dan penjaga tersenarai.', encrypted: 'Vault disulitkan', all: 'Semua dokumen', search: 'Cari dokumen...', uploaded: 'Dimuat naik', view: 'Lihat', download: 'Muat turun', preview: 'Pratonton PDF terjamin MediSync', previewText: 'Dokumen ini disulitkan dengan kunci perubatan peribadi anda. Tiada maklumat luaran dibocorkan.', closePreview: 'Tutup pratonton', uploadTitle: 'Muat naik dokumen perubatan / insurans', documentName: 'Nama / tajuk dokumen', category: 'Kategori dokumen', insurance: 'Insurans & kad perubatan', labs: 'Ujian darah & makmal', discharge: 'Surat discas hospital', prescription: 'Preskripsi ubat', chooseFile: 'Pilih fail (PDF / imej)', chooseFileText: 'Klik untuk pilih fail atau seret ke sini', fileSupport: 'PDF, PNG, JPG, WEBP sehingga 10MB', notes: 'Nota catatan', notesPlaceholder: 'Catatan tambahan mengenai dokumen', cancel: 'Batal', uploading: 'Memuat naik...', uploadVault: 'Muat naik ke vault', required: 'Sila isi tajuk dan pilih fail.', uploadError: 'Gagal memuat naik.', uploadNetwork: 'Ralat semasa memuat naik fail.' },
        symptoms: { title: 'Symptom summariser untuk doktor', eyebrow: 'Penyediaan temujanji doktor (intake assistant)', description: 'Masukkan simptom yang anda rasai. Sistem akan menstrukturkan laporan klinikal SOAP ringkas untuk dibaca oleh doktor.', form: 'Borang catatan simptom', primary: 'Simptom utama / sakit yang dirasai', onset: 'Mula berlaku (onset)', duration: 'Tempoh & kekerapan', severity: 'Skala kesakitan (1 - 10)', triggers: 'Faktor pencetus (bila rasa lebih teruk?)', accompanying: 'Simptom sampingan lain', treatments: 'Rawatan / langkah dicuba sendiri', report: 'Laporan ringkasan doktor (SOAP intake)', format: 'Format klinik', reportHint: 'Tunjukkan laporan ini kepada doktor atau jururawat semasa mengambil sejarah perubatan:', copy: 'Salin ringkasan untuk doktor', copied: 'Ringkasan berjaya disalin!', save: 'Simpan laporan', saved: 'Disimpan!', history: 'Sejarah perubatan pesakit', complaint: 'Aduan utama', onsetLabel: 'Mula berlaku', durationLabel: 'Tempoh', severityLabel: 'Kesakitan', triggersLabel: 'Faktor pencetus', associated: 'Simptom sampingan', pretreatments: 'Rawatan dicuba', patient: 'Pesakit' },
        terms: { title: 'Penyederhana istilah perubatan AI', eyebrow: 'Penterjemah istilah & laporan doktor', heading: 'Mudahkan istilah perubatan', description: 'Fahami jargon perubatan yang sukar dalam surat hospital, keputusan makmal, dan laporan diagnosis dengan bahasa mudah serta analogi harian.', search: 'Taip istilah perubatan...', translate: 'Terangkan dengan mudah', easy: 'Diterangkan dalam bahasa mudah', explanation: 'Penerangan mudah (tanpa jargon)', analogy: 'Analogi mudah difahami', takeaways: 'Perkara utama perlu diketahui', questions: 'Soalan untuk ditanya kepada doktor', copyQuestions: 'Salin soalan untuk temujanji', searchResult: 'Hasil carian istilah', generated: 'Istilah perubatan yang digunakan untuk menerangkan keadaan fizikal atau keputusan makmal.', questionOne: 'Apakah maksud istilah ini terhadap kesihatan saya?', questionTwo: 'Adakah rawatan susulan diperlukan?' },
        emergency: { iceTitle: 'Pengurusan profil kecemasan (ICE)', iceBadge: 'Lockscreen kecemasan ICE', iceHeading: 'Profil kecemasan in-case-of-emergency (ICE)', blood: 'Kumpulan darah', donor: 'Penderma organ', donorYes: 'Ya (berikrar)', donorNo: 'Tidak', weight: 'Berat (kg)', height: 'Tinggi (cm)', chronic: 'Penyakit kronik & alahan kritikal', allergy: 'Alahan ubat & makanan (amaran ketat)', history: 'Sejarah perubatan / penyakit kronik', medications: 'Ubat penting yang sedang diambil', purpose: 'Tujuan', active: 'Aktif', publicAccess: 'Kawalan akses awam', publicText: 'Mod akses awam mengehadkan fail peribadi, nombor insurans, dan dokumen sulit. Hanya data keselamatan nyawa ditunjukkan.', quickLink: 'Pautan pantas kecemasan', save: 'Kemaskini profil ICE', saved: 'Profil disimpan!', error: 'Ralat rangkaian. Sila cuba lagi.', sosTitle: 'SOS kecemasan & hospital terdekat', sosBadge: 'Talian kecemasan satu sentuhan', sosHeading: 'SOS & pencari hospital terdekat', sosText: 'Tekan butang kecemasan untuk menghantar lokasi semasa dan SMS kecemasan automatik kepada penjaga serta talian hospital terdekat.', press: 'Tekan SOS', alert: 'Amaran kecemasan dipancarkan!', sent: 'SMS & lokasi dihantar kepada penjaga', sending: 'Menghantar koordinat GPS & maklumat ICE...', cancel: 'Batal amaran SOS', contacts: 'Talian kecemasan utama', primary: 'Utama', hospitals: 'Hospital & jabatan kecemasan terdekat (GPS)', hospitalText: 'Senarai hospital zon merah berdekatan kediaman anda.', locationActive: 'Lokasi aktif', emergency24: 'Zon kecemasan 24 jam', clinic: 'Klinik kesihatan', callER: 'Panggil ER', navigate: 'Navigasi', driving: 'memandu' },
    },
};

const LanguageContext = createContext(null);

function readLanguage() {
    if (typeof window === 'undefined') return 'en';
    try { return window.localStorage.getItem('medisync-language') === 'ms' ? 'ms' : 'en'; } catch (error) { return 'en'; }
}

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState(readLanguage);

    useEffect(() => {
        try { window.localStorage.setItem('medisync-language', language); } catch (error) { /* optional preference */ }
    }, [language]);

    const value = useMemo(() => ({
        language,
        setLanguage,
        t: (key) => key.split('.').reduce((result, part) => result?.[part], translations[language]) || key,
    }), [language]);

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
    return context;
}
